name: Alexandre_workflow
on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
  pull_request:
    branches:
      - master
      - develop
    types:
      - opened
      - edited
  schedule:
    - cron: '0 0 1 * *'
  issues:
    types:
      - opened
      - labeled
  workflow_dispatch:
      
jobs:
  # This workflow contains a single job called "build"
  build:
   # The type of runner that the job will run on
   runs-on: ubuntu-latest

   # Steps represent a sequence of tasks that will be executed as part of the job
   steps:
     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     - uses: actions/checkout@v2

      # Runs a single command using the runners shell
     - name: Run a one-line script
       run: echo Hello, world! Today is $(date %c)
